function seqs=configSeqs2(video_path_UAV123)
dataSet = video_path_UAV123;

seqVTD={struct('name','soccer','path',[dataSet '\soccer\img\'],'startFrame',1,'endFrame',392,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),... 
    struct('name','matrix','path',[dataSet '\matrix\img\'],'startFrame',1,'endFrame',100,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','ironman','path',[dataSet '\ironman\img\'],'startFrame',1,'endFrame',166,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','deer','path',[dataSet '\deer\img\'],'startFrame',1,'endFrame',71,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','skating1','path',[dataSet '\skating1\img\'],'startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','shaking','path',[dataSet '\shaking\img\'],'startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','singer1','path',[dataSet '\singer1\img\'],'startFrame',1,'endFrame',351,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','singer2','path',[dataSet '\singer2\img\'],'startFrame',1,'endFrame',366,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};
seqIVT={struct('name','carDark','path',[dataSet '\carDark\img\'],'startFrame',1,'endFrame',393,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','car4','path',[dataSet '\car4\img\'],'startFrame',1,'endFrame',659,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','david2','path',[dataSet '\david2\img\'],'startFrame',1,'endFrame',537,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...    
    struct('name','sylvester','path',[dataSet '\sylvester\img\'],'startFrame',1,'endFrame',1345,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','trellis','path',[dataSet '\trellis\img\'],'startFrame',1,'endFrame',569,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','fish','path',[dataSet '\fish\img\'],'startFrame',1,'endFrame',476,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','mhyang','path',[dataSet '\mhyang\img\'],'startFrame',1,'endFrame',1490,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','david','path',[dataSet '\david\img\'],'startFrame',300,'endFrame',770,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};
seqOther={struct('name','coke','path',[dataSet '\coke\img\'],'startFrame',1,'endFrame',291,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','bolt','path',[dataSet '\bolt\img\'],'startFrame',1,'endFrame',350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','boy','path',[dataSet '\boy\img\'],'startFrame',1,'endFrame',602,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','dudek','path',[dataSet '\dudek\img\'],'startFrame',1,'endFrame',1145,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','crossing','path',[dataSet '\crossing\img\'],'startFrame',1,'endFrame',120,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','couple','path',[dataSet '\couple\img\'],'startFrame',1,'endFrame',140,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','football1','path',[dataSet '\football1\img\'],'startFrame',1,'endFrame',74,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','jogging-1','path',[dataSet '\jogging\img\'],'startFrame',1,'endFrame',307,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','jogging-2','path',[dataSet '\jogging\img\'],'startFrame',1,'endFrame',307,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','doll','path',[dataSet '\doll\img\'],'startFrame',1,'endFrame',3872,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','girl','path',[dataSet '\girl\img\'],'startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','walking2','path',[dataSet '\walking2\img\'],'startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','walking','path',[dataSet '\walking\img\'],'startFrame',1,'endFrame',412,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','fleetface','path',[dataSet '\fleetface\img\'],'startFrame',1,'endFrame',707,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','freeman1','path',[dataSet '\freeman1\img\'],'startFrame',1,'endFrame',326,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','freeman3','path',[dataSet '\freeman3\img\'],'startFrame',1,'endFrame',460,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','freeman4','path',[dataSet '\freeman4\img\'],'startFrame',1,'endFrame',283,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','david3','path',[dataSet '\david3\img\'],'startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','jumping','path',[dataSet '\jumping\img\'],'startFrame',1,'endFrame',313,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','carScale','path',[dataSet '\carScale\img\'],'startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','skiing','path',[dataSet '\skiing\img\'],'startFrame',1,'endFrame',81,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','dog1','path',[dataSet '\dog1\img\'],'startFrame',1,'endFrame',1350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','suv','path',[dataSet '\suv\img\'],'startFrame',1,'endFrame',945,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','motorRolling','path',[dataSet '\motorRolling\img\'],'startFrame',1,'endFrame',164,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','mountainBike','path',[dataSet '\mountainBike\img\'],'startFrame',1,'endFrame',228,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),... 
    struct('name','lemming','path',[dataSet '\lemming\img\'],'startFrame',1,'endFrame',1336,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','liquor','path',[dataSet '\liquor\img\'],'startFrame',1,'endFrame',1741,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','woman','path',[dataSet '\woman\img\'],'startFrame',1,'endFrame',597,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','faceocc1','path',[dataSet '\faceocc1\img\'],'startFrame',1,'endFrame',892,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','faceocc2','path',[dataSet '\faceocc2\img\'],'startFrame',1,'endFrame',812,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','basketball','path',[dataSet '\basketball\img\'],'startFrame',1,'endFrame',725,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','football','path',[dataSet '\football\img\'],'startFrame',1,'endFrame',362,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','subway','path',[dataSet '\subway\img\'],'startFrame',1,'endFrame',175,'nz',4,'ext','jpg','init_rect', [0 0 0 0]),...    
    struct('name','tiger1','path',[dataSet '\tiger1\img\'],'startFrame',1,'endFrame',354,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','tiger2','path',[dataSet '\tiger2\img\'],'startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};
seqOTB49_100={struct('name','Biker','path',[dataSet '\Biker\img\'],'startFrame',1,'endFrame',142,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Bird1','path',[dataSet '\Bird1\img\'],'startFrame',1,'endFrame',408,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Bird2','path',[dataSet '\Bird2\img\'],'startFrame',1,'endFrame',99,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','BlurBody','path',[dataSet '\BlurBody\img\'],'startFrame',1,'endFrame',334,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','BlurCar1','path',[dataSet '\BlurCar1\img\'],'startFrame',247,'endFrame',988,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','BlurCar2','path',[dataSet '\BlurCar2\img\'],'startFrame',1,'endFrame',585,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','BlurCar3','path',[dataSet '\BlurCar3\img\'],'startFrame',3,'endFrame',359,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','BlurCar4','path',[dataSet '\BlurCar4\img\'],'startFrame',18,'endFrame',397,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','BlurFace','path',[dataSet '\BlurFace\img\'],'startFrame',1,'endFrame',493,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','BlurOwl','path',[dataSet '\BlurOwl\img\'],'startFrame',1,'endFrame',631,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Board','path',[dataSet '\Board\img\'],'startFrame',1,'endFrame',698,'nz',5,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Bolt2','path',[dataSet '\Bolt2\img\'],'startFrame',1,'endFrame',293,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Box','path',[dataSet '\Box\img\'],'startFrame',1,'endFrame',1161,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Car1','path',[dataSet '\Car1\img\'],'startFrame',1,'endFrame',1020,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Car2','path',[dataSet '\Car2\img\'],'startFrame',1,'endFrame',913,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Car24','path',[dataSet '\Car24\img\'],'startFrame',1,'endFrame',3059,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','ClifBar','path',[dataSet '\ClifBar\img\'],'startFrame',1,'endFrame',472,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Coupon','path',[dataSet '\Coupon\img\'],'startFrame',1,'endFrame',327,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Crowds','path',[dataSet '\Crowds\img\'],'startFrame',1,'endFrame',347,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Dancer','path',[dataSet '\Dancer\img\'],'startFrame',1,'endFrame',225,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Dancer2','path',[dataSet '\Dancer2\img\'],'startFrame',1,'endFrame',150,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...   
    struct('name','Diving','path',[dataSet '\Diving\img\'],'startFrame',1,'endFrame',215,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Dog','path',[dataSet '\Dog\img\'],'startFrame',1,'endFrame',127,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','DragonBaby','path',[dataSet '\DragonBaby\img\'],'startFrame',1,'endFrame',113,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Girl2','path',[dataSet '\Girl2\img\'],'startFrame',1,'endFrame',1500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Gym','path',[dataSet '\Gym\img\'],'startFrame',1,'endFrame',767,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Human2','path',[dataSet '\Human2\img\'],'startFrame',1,'endFrame',1128,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Human3','path',[dataSet '\Human3\img\'],'startFrame',1,'endFrame',1698,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Human4','path',[dataSet '\Human4\img\'],'startFrame',1,'endFrame',667,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Human5','path',[dataSet '\Human5\img\'],'startFrame',1,'endFrame',713,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Human6','path',[dataSet '\Human6\img\'],'startFrame',1,'endFrame',792,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Human7','path',[dataSet '\Human7\img\'],'startFrame',1,'endFrame',250,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Human8','path',[dataSet '\Human8\img\'],'startFrame',1,'endFrame',128,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Human9','path',[dataSet '\Human9\img\'],'startFrame',1,'endFrame',305,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Jump','path',[dataSet '\Jump\img\'],'startFrame',1,'endFrame',122,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','KiteSurf','path',[dataSet '\KiteSurf\img\'],'startFrame',1,'endFrame',84,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Man','path',[dataSet '\Man\img\'],'startFrame',1,'endFrame',134,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Panda','path',[dataSet '\Panda\img\'],'startFrame',1,'endFrame',1000,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','RedTeam','path',[dataSet '\RedTeam\img\'],'startFrame',1,'endFrame',1918,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Rubik','path',[dataSet '\Rubik\img\'],'startFrame',1,'endFrame',1997,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Skater','path',[dataSet '\Skater\img\'],'startFrame',1,'endFrame',160,'nz',4,'ext','jpg','init_rect', [0,0,0,0])...
    struct('name','Skater2','path',[dataSet '\Skater2\img\'],'startFrame',1,'endFrame',435,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Skating2-1','path',[dataSet '\Skating2\img\'],'startFrame',1,'endFrame',473,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Skating2-2','path',[dataSet '\Skating2\img\'],'startFrame',1,'endFrame',473,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Surfer','path',[dataSet '\Surfer\img\'],'startFrame',1,'endFrame',376,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Toy','path',[dataSet '\Toy\img\'],'startFrame',1,'endFrame',271,'nz',4,'ext','jpg','init_rect',[0,0,0,0])...
    struct('name','Trans','path',[dataSet '\Trans\img\'],'startFrame',1,'endFrame',124,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Twinnings','path',[dataSet '\Twinnings\img\'],'startFrame',1,'endFrame',472,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
    struct('name','Vase','path',[dataSet '\Vase\img\'],'startFrame',1,'endFrame',271,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};
% seqOTB50={struct('name','basketball','path',[dataSet '\basketball\img\'],'startFrame',1,'endFrame',725,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Biker','path',[dataSet '\Biker\img\'],'startFrame',1,'endFrame',142,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Bird1','path',[dataSet '\Bird1\img\'],'startFrame',1,'endFrame',408,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','BlurBody','path',[dataSet '\BlurBody\img\'],'startFrame',1,'endFrame',334,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','BlurCar2','path',[dataSet '\BlurCar2\img\'],'startFrame',1,'endFrame',585,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','BlurFace','path',[dataSet '\BlurFace\img\'],'startFrame',1,'endFrame',493,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','BlurOwl','path',[dataSet '\BlurOwl\img\'],'startFrame',1,'endFrame',631,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','bolt','path',[dataSet '\bolt\img\'],'startFrame',1,'endFrame',350,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Box','path',[dataSet '\Box\img\'],'startFrame',1,'endFrame',1161,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Car1','path',[dataSet '\Car1\img\'],'startFrame',1,'endFrame',1020,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','car4','path',[dataSet '\car4\img\'],'startFrame',1,'endFrame',659,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','carDark','path',[dataSet '\carDark\img\'],'startFrame',1,'endFrame',393,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','carScale','path',[dataSet '\carScale\img\'],'startFrame',1,'endFrame',252,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','ClifBar','path',[dataSet '\ClifBar\img\'],'startFrame',1,'endFrame',472,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','couple','path',[dataSet '\couple\img\'],'startFrame',1,'endFrame',140,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Crowds','path',[dataSet '\Crowds\img\'],'startFrame',1,'endFrame',347,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','david','path',[dataSet '\david\img\'],'startFrame',300,'endFrame',770,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','deer','path',[dataSet '\deer\img\'],'startFrame',1,'endFrame',71,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Diving','path',[dataSet '\Diving\img\'],'startFrame',1,'endFrame',215,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','DragonBaby','path',[dataSet '\DragonBaby\img\'],'startFrame',1,'endFrame',113,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','dudek','path',[dataSet '\dudek\img\'],'startFrame',1,'endFrame',1145,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','football','path',[dataSet '\football\img\'],'startFrame',1,'endFrame',362,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','freeman4','path',[dataSet '\freeman4\img\'],'startFrame',1,'endFrame',283,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','girl','path',[dataSet '\girl\img\'],'startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Human3','path',[dataSet '\Human3\img\'],'startFrame',1,'endFrame',1698,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Human4','path',[dataSet '\Human4\img\'],'startFrame',1,'endFrame',667,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Human6','path',[dataSet '\Human6\img\'],'startFrame',1,'endFrame',792,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Human9','path',[dataSet '\Human9\img\'],'startFrame',1,'endFrame',305,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','ironman','path',[dataSet '\ironman\img\'],'startFrame',1,'endFrame',166,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Jump','path',[dataSet '\Jump\img\'],'startFrame',1,'endFrame',122,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','jumping','path',[dataSet '\jumping\img\'],'startFrame',1,'endFrame',313,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','liquor','path',[dataSet '\liquor\img\'],'startFrame',1,'endFrame',1741,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','matrix','path',[dataSet '\matrix\img\'],'startFrame',1,'endFrame',100,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','motorRolling','path',[dataSet '\motorRolling\img\'],'startFrame',1,'endFrame',164,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Panda','path',[dataSet '\Panda\img\'],'startFrame',1,'endFrame',1000,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','RedTeam','path',[dataSet '\RedTeam\img\'],'startFrame',1,'endFrame',1918,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','shaking','path',[dataSet '\shaking\img\'],'startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','singer2','path',[dataSet '\singer2\img\'],'startFrame',1,'endFrame',366,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','skating1','path',[dataSet '\skating1\img\'],'startFrame',1,'endFrame',400,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Skating2-1','path',[dataSet '\Skating2\img\'],'startFrame',1,'endFrame',473,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Skating2-2','path',[dataSet '\Skating2\img\'],'startFrame',1,'endFrame',473,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','skiing','path',[dataSet '\skiing\img\'],'startFrame',1,'endFrame',81,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','soccer','path',[dataSet '\soccer\img\'],'startFrame',1,'endFrame',392,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','Surfer','path',[dataSet '\Surfer\img\'],'startFrame',1,'endFrame',376,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','sylvester','path',[dataSet '\sylvester\img\'],'startFrame',1,'endFrame',1345,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','tiger2','path',[dataSet '\tiger2\img\'],'startFrame',1,'endFrame',365,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','trellis','path',[dataSet '\trellis\img\'],'startFrame',1,'endFrame',569,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','walking2','path',[dataSet '\walking2\img\'],'startFrame',1,'endFrame',500,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','walking','path',[dataSet '\walking\img\'],'startFrame',1,'endFrame',412,'nz',4,'ext','jpg','init_rect', [0,0,0,0]),...
%     struct('name','woman','path',[dataSet '\woman\img\'],'startFrame',1,'endFrame',597,'nz',4,'ext','jpg','init_rect', [0,0,0,0])};
% seqs=[seqIVT,seqVTD,seqOther]; %OTB-2013
seqs=[seqIVT,seqVTD,seqOther,seqOTB49_100];   %OTB100
% seqs = seqOTB50;   %OTB50
